### ISSUE TITLE
Compiling project

### ISSUE THREAD

**Issue by paberr** [dignifiedquire/rust-accumulators#5]
Hey,

I was trying to compile the project and run the benchmarks (on the `master` branch).
However, I get a bunch of compilation errors with both stable and current nightly rust.

Most of the errors seem to be related to your BigInt implementation, which is directly downloaded from your [GitHub](https://github.com/dignifiedquire/num-bigint) fork.
I guess that you did some changes there that made it incompatible with this library.

Can you point me to a version/commit in both libraries that currently works and can be compiled?

Thanks!

**Comment by dignifiedquire** [comment]
Hey sorry about that, I just pushed a fix for this to `master` please let me know if that does not work for you

**Comment by paberr** [comment]
Works perfectly, thanks! 👍

**Comment by lamei1224** [comment]
@paberr  hi,I also encountered the same compilation problem, how did you solve it?
![error 0658](https://user-images.githubusercontent.com/55862430/86507312-f4d7fc00-be09-11ea-9deb-80759f0b5fe7.png)
![error0599](https://user-images.githubusercontent.com/55862430/86507315-f73a5600-be09-11ea-8733-094bc9a90f09.png)
